name: Daily Market Digest

on:
  schedule:
    - cron: '45 20 * * 1-5'  # Runs at 4:45 PM EDT Mon–Fri (8:45 PM UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install yfinance

      - name: Run market digest script
        run: python get_market_digest.py

      - name: Commit and push updated digest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/index.html
          git commit -m "Update daily market digest [skip ci]" || echo "No changes to commit"
          git push
